version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Exponer el puerto de la aplicación
    environment:
      SPRING_DATA_MONGODB_HOST: db  # Host de MongoDB en el contenedor
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: fundsdb
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ashmeddiazg@gmail.com
      SPRING_MAIL_PASSWORD: zexaywgqcrvcnaci
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: 2000
    depends_on:
      - db

  db:
    image: mongo:5.0
    container_name: mongo-fundsdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fundsdb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
